In [1]:
!pip install numpy

zsh:1: /Users/muqeeth/Desktop/ML_Student 1_Project/.venv/bin/pip: bad interpreter: /Users/muqeeth/Desktop/ML_Student_Project/.venv/bin/python: no such file or directory

In [2]:
import numpy as np

In [3]:
!pip install pandas

zsh:1: /Users/muqeeth/Desktop/ML_Student 1_Project/.venv/bin/pip: bad interpreter: /Users/muqeeth/Desktop/ML_Student_Project/.venv/bin/python: no such file or directory

In [4]:
!pip install scikit-learn

zsh:1: /Users/muqeeth/Desktop/ML_Student 1_Project/.venv/bin/pip: bad interpreter: /Users/muqeeth/Desktop/ML_Student_Project/.venv/bin/python: no such file or directory

In [6]:
import numpy as np
import pandas as pd
import sklearn

In [9]:
df = pd.read_csv("/Users/muqeeth/Desktop/ML_Student 1_Project/Student Scores Data (1).csv")

In [10]:
df

    Study_Hours Attendance (%) Weekly_Test_Score Final_Exam_Score
0           6.0             93                56               69
1           4.7             92                38               81
2           6.3             82                91               74
3           8.0             83                66               46
4           4.5             96                80               99
5           4.5             94                55            fifty
6           8.2             99               NaN               65
7           6.5             81                88               87
8           4.1             86                61               96
9           6.1             94                81               91
10          4.1             60                91               99
11          4.1             94                87               88
12          5.5             96            eighty               41
13          1.2             73                41               40
14          1.6             62                68               87
15          3.9        seventy                31               51
16          3.0             64                32               44
17          5.6             85                85               76
18          3.2             73                88               71
19          2.2             98                31               98
20          7.9             86                31               94
21          4.5             68                83               48
22          5.1             74                30               80
23          2.2             74                48               74
24          3.9             85                31               58
25          5.2             80               NaN               87
26          NaN             91                73               55
27          5.8             98                61               42
28          3.8             91                99               59
29          NaN             63                61               63
30          3.8             89                97               93
31          8.7             96                84               95
32          5.0             82                85               72
33          2.9             98                46               63
34          6.6             74                67               91
35          2.6             88                53          unknown
36          NaN            NaN                98               88
37          1.1             72                99               47
38          2.3             91                40              NaN
39          5.4             66                45               77
40          6.5             81                88               79
41          5.3             87                99               59
42          4.8             61                32               74
43          4.4             65                49               87
44          2.0             87                88               64
45          NaN             87                65               74
46          4.1             79                48               64
47          7.1             89                96               68
48          5.7             70                48               57
49          1.5             87                49               85
50          5.6             84                81               57
51          4.2             98                62               41
52          3.6             92                69               93
53          6.2             60                68               74
54          NaN             86                30               55
55          6.9         ninety                40               80
56          3.3             62                86               75
57          4.4             98                79               72
58          5.7             85                52               43
59          7.0             67                60               72

In [11]:
df.head()

   Study_Hours Attendance (%) Weekly_Test_Score Final_Exam_Score
0          6.0             93                56               69
1          4.7             92                38               81
2          6.3             82                91               74
3          8.0             83                66               46
4          4.5             96                80               99

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Study_Hours        55 non-null     float64
 1   Attendance (%)     59 non-null     str
 2   Weekly_Test_Score  58 non-null     str
 3   Final_Exam_Score   59 non-null     str
dtypes: float64(1), str(3)
memory usage: 2.4 KB

In [14]:
df.shape

(60, 4)

In [15]:
print(df.isnull().sum())

Study_Hours          5
Attendance (%)       1
Weekly_Test_Score    2
Final_Exam_Score     1
dtype: int64

In [16]:
df.dropna(inplace=True)

In [17]:
print(df.isnull().sum())

Study_Hours          0
Attendance (%)       0
Weekly_Test_Score    0
Final_Exam_Score     0
dtype: int64

In [18]:
df=df[df['Attendance (%)'].str.isnumeric()]

In [19]:
df

    Study_Hours Attendance (%) Weekly_Test_Score Final_Exam_Score
0           6.0             93                56               69
1           4.7             92                38               81
2           6.3             82                91               74
3           8.0             83                66               46
4           4.5             96                80               99
5           4.5             94                55            fifty
7           6.5             81                88               87
8           4.1             86                61               96
9           6.1             94                81               91
10          4.1             60                91               99
11          4.1             94                87               88
12          5.5             96            eighty               41
13          1.2             73                41               40
14          1.6             62                68               87
16          3.0             64                32               44
17          5.6             85                85               76
18          3.2             73                88               71
19          2.2             98                31               98
20          7.9             86                31               94
21          4.5             68                83               48
22          5.1             74                30               80
23          2.2             74                48               74
24          3.9             85                31               58
27          5.8             98                61               42
28          3.8             91                99               59
30          3.8             89                97               93
31          8.7             96                84               95
32          5.0             82                85               72
33          2.9             98                46               63
34          6.6             74                67               91
35          2.6             88                53          unknown
37          1.1             72                99               47
39          5.4             66                45               77
40          6.5             81                88               79
41          5.3             87                99               59
42          4.8             61                32               74
43          4.4             65                49               87
44          2.0             87                88               64
46          4.1             79                48               64
47          7.1             89                96               68
48          5.7             70                48               57
49          1.5             87                49               85
50          5.6             84                81               57
51          4.2             98                62               41
52          3.6             92                69               93
53          6.2             60                68               74
56          3.3             62                86               75
57          4.4             98                79               72
58          5.7             85                52               43
59          7.0             67                60               72

In [20]:
df=df[df['Weekly_Test_Score'].str.isnumeric()]

In [21]:
df=df[df['Final_Exam_Score'].str.isnumeric()]

In [22]:
df

    Study_Hours Attendance (%) Weekly_Test_Score Final_Exam_Score
0           6.0             93                56               69
1           4.7             92                38               81
2           6.3             82                91               74
3           8.0             83                66               46
4           4.5             96                80               99
7           6.5             81                88               87
8           4.1             86                61               96
9           6.1             94                81               91
10          4.1             60                91               99
11          4.1             94                87               88
13          1.2             73                41               40
14          1.6             62                68               87
16          3.0             64                32               44
17          5.6             85                85               76
18          3.2             73                88               71
19          2.2             98                31               98
20          7.9             86                31               94
21          4.5             68                83               48
22          5.1             74                30               80
23          2.2             74                48               74
24          3.9             85                31               58
27          5.8             98                61               42
28          3.8             91                99               59
30          3.8             89                97               93
31          8.7             96                84               95
32          5.0             82                85               72
33          2.9             98                46               63
34          6.6             74                67               91
37          1.1             72                99               47
39          5.4             66                45               77
40          6.5             81                88               79
41          5.3             87                99               59
42          4.8             61                32               74
43          4.4             65                49               87
44          2.0             87                88               64
46          4.1             79                48               64
47          7.1             89                96               68
48          5.7             70                48               57
49          1.5             87                49               85
50          5.6             84                81               57
51          4.2             98                62               41
52          3.6             92                69               93
53          6.2             60                68               74
56          3.3             62                86               75
57          4.4             98                79               72
58          5.7             85                52               43
59          7.0             67                60               72

In [23]:
df.info()

<class 'pandas.DataFrame'>
Index: 47 entries, 0 to 59
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Study_Hours        47 non-null     float64
 1   Attendance (%)     47 non-null     str
 2   Weekly_Test_Score  47 non-null     str
 3   Final_Exam_Score   47 non-null     str
dtypes: float64(1), str(3)
memory usage: 2.1 KB

In [24]:
df['Attendance (%)']=df['Attendance (%)'].astype(int)

In [25]:
df.info()

<class 'pandas.DataFrame'>
Index: 47 entries, 0 to 59
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Study_Hours        47 non-null     float64
 1   Attendance (%)     47 non-null     int64
 2   Weekly_Test_Score  47 non-null     str
 3   Final_Exam_Score   47 non-null     str
dtypes: float64(1), int64(1), str(2)
memory usage: 2.0 KB

In [26]:
df['Weekly_Test_Score']=df['Weekly_Test_Score'].astype(int)

In [27]:
df['Final_Exam_Score']=df['Final_Exam_Score'].astype(int)

In [28]:
df.info()

<class 'pandas.DataFrame'>
Index: 47 entries, 0 to 59
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Study_Hours        47 non-null     float64
 1   Attendance (%)     47 non-null     int64
 2   Weekly_Test_Score  47 non-null     int64
 3   Final_Exam_Score   47 non-null     int64
dtypes: float64(1), int64(3)
memory usage: 1.8 KB

In [29]:
from sklearn.model_selection import train_test_split

df.info()

<class 'pandas.DataFrame'>
Index: 47 entries, 0 to 59
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Study_Hours        47 non-null     float64
 1   Attendance (%)     47 non-null     int64
 2   Weekly_Test_Score  47 non-null     int64
 3   Final_Exam_Score   47 non-null     int64
dtypes: float64(1), int64(3)
memory usage: 1.8 KB

In [30]:
x = df[["Study_Hours","Attendance (%)","Weekly_Test_Score"]]
y = df[["Final_Exam_Score"]]

In [31]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=47)

In [32]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [33]:
y_pred = model.predict(x_test)

In [34]:
y_pred

array([[75.060627  ],
       [77.67273541],
       [73.7689856 ],
       [71.9252459 ],
       [75.9815012 ],
       [75.64691605],
       [76.14363618],
       [68.6432214 ],
       [70.83489906],
       [70.51275466]])

In [35]:
from sklearn.metrics import r2_score
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import mean_absolute_error

r2 = r2_score(y_pred,y_test)
print(r2)

rmse = root_mean_squared_error(y_pred,y_test)
print(rmse)

mae = mean_absolute_error(y_pred,y_test)
print(mae)

-20.052637561284868
12.947535794653557
10.79141105496023

In [36]:
import joblib

joblib.dump(model , "lr.pkl")

['lr.pkl']

In [37]:
!pip install streamlit

zsh:1: /Users/muqeeth/Desktop/ML_Student 1_Project/.venv/bin/pip: bad interpreter: /Users/muqeeth/Desktop/ML_Student_Project/.venv/bin/python: no such file or directory

In [38]:
import streamlit